-- Run this in Supabase SQL Editor (left sidebar → SQL Editor → New Query)

-- Products table
create table products (
  id bigint primary key generated by default as identity,
  name text not null,
  sku text not null,
  category text default 'General',
  stock int default 0,
  reorder int default 20,
  price numeric default 0,
  velocity numeric default 0,
  lead int default 7,
  history jsonb default '[]',
  image text default null
);
alter table products enable row level security;
create policy "public_access" on products for all to anon using (true) with check (true);

-- Users table
create table users (
  id text primary key,
  display_name text not null,
  username_hash text unique not null,
  password_hash text not null,
  phone_hash text default '',
  color text default '#00d4ff',
  created_at timestamptz default now()
);
alter table users enable row level security;
create policy "public_access" on users for all to anon using (true) with check (true);

-- Sales table
create table sales (
  id bigint primary key generated by default as identity,
  product_name text,
  sku text,
  qty int,
  total numeric,
  sold_by text,
  sold_at timestamptz default now()
);
alter table sales enable row level security;
create policy "public_access" on sales for all to anon using (true) with check (true);

-- Seed products
insert into products (id, name, sku, category, stock, reorder, price, velocity, lead, history) values
(1, 'Wireless Mouse', 'WM-001', 'Electronics', 12, 20, 599, 2.8, 7, '[42,38,35,28,22,18,15,12]'),
(2, 'USB-C Hub 7-Port', 'UC-007', 'Electronics', 45, 15, 1299, 1.5, 10, '[60,58,55,52,50,48,46,45]'),
(3, 'A4 Paper Ream', 'PP-A4', 'Office Supplies', 8, 30, 249, 5.2, 3, '[80,72,65,55,44,32,20,8]'),
(4, 'Ballpoint Pen Box', 'BP-100', 'Office Supplies', 0, 50, 89, 7.1, 5, '[90,80,65,50,35,20,8,0]'),
(5, 'Lab Beaker 500ml', 'LB-500', 'Lab Equipment', 60, 10, 349, 0.8, 14, '[65,64,63,62,62,61,61,60]'),
(6, 'Bubble Wrap Roll', 'BW-30', 'Packaging', 25, 20, 180, 2.2, 5, '[40,38,35,32,30,28,26,25]'),
(7, 'Mineral Water Case', 'MW-24', 'Beverages', 18, 24, 320, 3.5, 2, '[50,46,42,38,33,28,23,18]'),
(8, 'Copper Wire Spool', 'CW-10M', 'Raw Materials', 100, 30, 750, 1.2, 21, '[108,107,105,104,103,102,101,100]');

select setval(pg_get_serial_sequence('products', 'id'), 8);
